AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'The AWS CloudFormation template for this Serverless application'
Parameters:
  DBHOST:
    Type: String
    Default: ${{secrets.DBHOST}}
  DBNAME:
    Type: String
    Default: ${{secrets.DBNAME}}
  DBUSER:
    Type: String
    Default: ${{secrets.DBUSER}}
  DBPASSWORD:
    Type: String
    Default: ${{secrets.DBPASSWORD}}

Resources:
  LogLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_log.lambda_handler
      CodeUri: ../lambdas/log/
      Runtime: python3.9
      MemorySize: 128
      Timeout: 200
      Environment:
        Variables:
          VERSION: "1.0.66"
          DBHost: !Ref DBHOST
          DBName: !Ref DBNAME
          DBUser: !Ref DBUSER
          DBPassword: !Ref DBPASSWORD
      Description: "Serveless function to store and process log plataform data."
