AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'The AWS CloudFormation template for this Serverless application'
Resources:
  LogLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_log.lambda_handler
      CodeUri: ../lambdas/log/
      Runtime: python3.9
      MemorySize: 128
      Timeout: 200
      Environment:
        Variables:
          VERSION: "1.0.63"
          DB_HOST: !Ref '${{ secrets.DB_HOST }}'
          DB_NAME: !Ref '${{ secrets.DB_NAME }}'
          DB_USER: !Ref '${{ secrets.DB_USER }}'
          DB_PASSWORD: !Ref '${{ secrets.DB_PASSWORD }}'
          DB_PORT: !Ref '${{ secrets.DB_PORT }}'
      Description: "Serveless function to store and process log plataform data."
