AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'The AWS CloudFormation template for this Serverless application'

Parameters:
  DBHOST:
    Type: String
  DBNAME:
    Type: String
  DBUSER:
    Type: String
  DBPORT:
    Type: Number
  DBPASSWORD:
    Type: String

Resources:
  MyHttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: motivy-analytics-api

  LogLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_log.lambda_handler
      CodeUri: ../lambdas/log/
      Runtime: python3.9
      MemorySize: 128
      Timeout: 200
      Environment:
        Variables:
          VERSION: "1.0.72"
          DBHost: !Ref DBHOST
          DBName: !Ref DBNAME
          DBUser: !Ref DBUSER
          DBPort: !Ref DBPORT
          DBPassword: !Ref DBPASSWORD
      Events:
        HttpGetEvent:
          Type: Api
          Properties:
            Path: /getLog
            Method: get
            RestApiId: !Ref MyHttpApi
        HttpPostEvent:
          Type: Api
          Properties:
            Path: /postLog
            Method: post
            RestApiId: !Ref MyHttpApi
      Description: "Serveless function to store and process log plataform data."
