AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'The AWS CloudFormation template for this Serverless application'
Resources:
  LogLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_log.lambda_handler
      CodeUri: ../lambdas/log/
      Runtime: python3.9
      MemorySize: 128
      Timeout: 200
      Environment:
        Variables:
          VERSION: "1.0.64"
          DBHost: !Sub "${{ secrets.DBHOST }}"
          DBName: !Sub "${{ secrets.DBNAME }}"
          DBUser: !Sub "${{ secrets.DBUSER }}"
          DBPort: !Sub "${{ secrets.DBPORT }}"
          DBPassword: !Sub "${{ secrets.DBPASSWORD }}"
      Description: "Serveless function to store and process log plataform data."
