AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'The AWS CloudFormation template for this Serverless application'
Resources:
  LogLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_log.lambda_handler
      CodeUri: ./lambdas/log/lambda_log.py
      Runtime: python3.9
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          VERSION: "1.0.12"
      Description: "Serveless function to store and process log plataform data."
      Layers:
        - !Ref LogLambdaLayer

  # Define the package options
      PackageType: Zip
      Metadata:
        AWS::CloudFormation::Package:
          # Define the S3 bucket and prefix to use
          S3Bucket: motivy-analytics
          S3Prefix: reck-pckgs
          # Add the Python requirements to the package
          PythonRequirements:
            - requirements.txt
