AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'The AWS CloudFormation template for this Serverless application'
Parameters:
  DB_HOST:
    Type: String
  DB_NAME:
    Type: String
  DB_USER:
    Type: String
  DB_PASSWORD:
    Type: String

Resources:
  LogLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_log.lambda_handler
      CodeUri: ../lambdas/log/
      Runtime: python3.9
      MemorySize: 128
      Timeout: 200
      Environment:
        Variables:
          VERSION: "1.0.63"
          DB_HOST: !Sub "${{resolve:secrets.${{ref DB_HOST}}}}"
          DB_NAME: !Sub "${{resolve:secrets.${{ref DB_NAME}}}}"
          DB_USER: !Sub "${{resolve:secrets.${{ref DB_USER}}}}"
          DB_PASSWORD: !Sub "${{resolve:secrets.${{ref DB_PASSWORD}}}}"
      Description: "Serveless function to store and process log plataform data."
